import {
  Baby,
  Banknote,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Coffee,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gift,
  GraduationCap,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  MapPin,
  PartyPopper,
  PawPrint,
  Pencil,
  Percent,
  Pill,
  Plane,
  Receipt,
  RotateCcw,
  Scissors,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sofa,
  Tag,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from '@/components/icons';
import type { AccountGroup } from '@/lib/domain/expenses';

/** Icon keys stored on categories (the domain stays free of UI imports). */
const categoryIcons: Record<string, LucideIcon> = {
  food: Utensils,
  coffee: Coffee,
  transport: Bus,
  car: Car,
  fuel: Fuel,
  travel: Plane,
  home: House,
  household: Sofa,
  family: Users,
  heart: Heart,
  social: PartyPopper,
  gift: Gift,
  sports: Dumbbell,
  hometown: MapPin,
  mobile: Smartphone,
  grooming: Scissors,
  stationery: Pencil,
  shops: ShoppingBag,
  medicine: Pill,
  health: HeartPulse,
  gadgets: Headphones,
  education: GraduationCap,
  entertainment: Film,
  pets: PawPrint,
  clothing: Shirt,
  books: BookOpen,
  baby: Baby,
  bills: Receipt,
  utilities: Zap,
  salary: Briefcase,
  freelance: Laptop,
  interest: Percent,
  refund: RotateCcw,
  other: Tag,
};

export const categoryIconKeys = Object.keys(categoryIcons);

export const iconFor = (key: string | undefined): LucideIcon => (key && categoryIcons[key]) || Tag;

export const accountGroupIcons: Record<AccountGroup, LucideIcon> = {
  cash: Banknote,
  bank: Landmark,
  card: CreditCard,
  wallet: Wallet,
  investment: TrendingUp,
  loan: HandCoins,
};

/** Fixed tint per account group, so the same kind of account always looks the same. */
export const accountGroupTints: Record<AccountGroup, number> = {
  cash: 0,
  bank: 2,
  card: 3,
  wallet: 5,
  investment: 1,
  loan: 4,
};
