import React from 'react';
import { Eye, GraduationCap, Plus, Save, Sparkles, Trash2, UserRound } from 'lucide-react';
import type { PortfolioData, PortfolioProject, PortfolioSkill } from '@/features/portfolio/model/portfolio';
import PortfolioExperienceEditor from '@/features/portfolio/components/PortfolioExperienceEditor';
import '@/shared/styles/portfolio-editor.css';

type Props = { value: PortfolioData; onSave: (value: PortfolioData) => void | Promise<void>; onPreview: () => void };

export default function PortfolioEditor({ value, onSave, onPreview }: Props) {
  const [draft, setDraft] = React.useState(value);
  const [notice, setNotice] = React.useState('');
  const [saving, setSaving] = React.useState(false);
  const [imagePreviewFailed, setImagePreviewFailed] = React.useState(false);
  React.useEffect(() => setDraft(value), [value]);
  React.useEffect(() => setImagePreviewFailed(false), [draft.profileImage]);
  const update = (key: keyof PortfolioData, next: unknown) => setDraft((old) => ({ ...old, [key]: next }));
  const updateProject = (index: number, key: keyof PortfolioProject, next: string) => update('projects', draft.projects.map((item, i) => i === index ? { ...item, [key]: next } : item));
  const updateSkill = (index: number, key: keyof PortfolioSkill, next: string) => update('skills', draft.skills.map((item, i) => i === index ? { ...item, [key]: next } : item));
  const save = async () => {
    setSaving(true); setNotice('');
    try {
      await onSave(draft);
      setNotice('Portfolio saved. Your public page is updated.'); window.setTimeout(() => setNotice(''), 3200); window.scrollTo({ top: 0, behavior: 'smooth' });
    } catch (error) {
      setNotice(error instanceof Error ? error.message : 'Could not save the portfolio. Try again.');
    } finally { setSaving(false); }
  };
  const removeDraftItem = (label: string, remove: () => void) => { if (window.confirm(`Remove ${label} from the portfolio draft?`)) remove(); };
  const field = (label: string, key: keyof PortfolioData, placeholder = '', multiline = false, type = 'text') => <label className={`portfolio-field${multiline ? ' is-multiline' : ''}`} key={String(key)}><span>{label}</span>{multiline ? <textarea value={String(draft[key])} onChange={(event) => update(key, event.target.value)} placeholder={placeholder} rows={3}/> : <input type={type} value={String(draft[key])} onChange={(event) => update(key, event.target.value)} placeholder={placeholder}/>}</label>;
  return <div className="portfolio-editor"><header className="editor-page-heading"><div><span className="editor-eyebrow"><Sparkles size={13}/> PORTFOLIO CMS</span><h1>Edit your portfolio</h1><p>Update the public profile and add or remove sections. Save to publish your changes.</p></div><div className="editor-heading-actions"><button type="button" className="editor-preview-button" onClick={onPreview}><Eye size={15}/> View public page</button><button type="button" className="editor-save-button" onClick={() => void save()} disabled={saving}><Save size={15}/> {saving ? 'Saving…' : 'Save changes'}</button></div></header>{notice && <div className="editor-saved-notice" role="status">{notice}</div>}
    <section className="editor-card"><div className="editor-card-heading"><span className="editor-section-icon"><UserRound size={17}/></span><div><h2>Profile</h2><p>The headline and introduction visitors see first.</p></div></div><div className="editor-fields-grid">{field('Name', 'fullName', 'Your name')}{field('Professional role', 'role', 'e.g. Software Engineer')}{field('Location', 'city', 'City, Country')}{field('Experience label', 'yearsExperience', 'e.g. 2+')}{field('Availability note', 'availability', 'Optional, e.g. Open to opportunities')}{field('Hero headline', 'headline', 'A short statement about your work', true)}{field('Introduction', 'intro', 'A few sentences about you', true)}<label className="portfolio-field profile-image-url"><span>Profile image URL or public file path</span><input value={draft.profileImage} onChange={(event) => update('profileImage', event.target.value)} placeholder="/profile.jpg or https://…"/></label><div className="portfolio-image-settings"><div className="portfolio-image-preview">{draft.profileImage && !imagePreviewFailed ? <img loading="lazy" decoding="async" src={draft.profileImage} alt="Profile image preview" onError={() => setImagePreviewFailed(true)}/> : <span>{imagePreviewFailed ? 'Image could not be loaded. Check the path or URL.' : 'Enter an image path to preview'}</span>}</div></div></div></section>
    <PortfolioExperienceEditor value={draft.experience} onChange={(experience) => update('experience', experience)}/> 
    <section className="editor-card"><div className="editor-card-heading"><span className="editor-section-icon"><Sparkles size={17}/></span><div><h2>Projects</h2><p>Selected work shown on the portfolio page. Add links when a demo or repository is public.</p></div><button type="button" className="editor-add-button" onClick={() => update('projects', [...draft.projects, { type: '', title: '', summary: '', stack: '', impact: '', liveUrl: '', sourceUrl: '' }])}><Plus size={14}/> Add project</button></div><div className="editor-repeat-list">{draft.projects.map((item, index) => <article className="editor-repeat-card" key={index}><div className="editor-repeat-title"><strong>Project {String(index + 1).padStart(2, '0')}</strong><button type="button" className="editor-remove-button" onClick={() => removeDraftItem(item.title || `project ${index + 1}`, () => update('projects', draft.projects.filter((_, i) => i !== index)))} aria-label="Remove project"><Trash2 size={14}/></button></div><div className="editor-fields-grid">{(['type','title'] as const).map((key) => <label className="portfolio-field" key={key}><span>{key === 'type' ? 'Project type / category' : 'Project title'}</span><input value={item[key]} onChange={(event) => updateProject(index, key, event.target.value)}/></label>)}<label className="portfolio-field is-multiline"><span>Project summary</span><textarea rows={3} value={item.summary} onChange={(event) => updateProject(index, 'summary', event.target.value)}/></label><label className="portfolio-field is-multiline"><span>Outcome / impact · optional</span><textarea rows={2} value={item.impact || ''} onChange={(event) => updateProject(index, 'impact', event.target.value)} placeholder="What changed because of this project?"/></label><label className="portfolio-field"><span>Technology tags · comma separated</span><input value={item.stack} onChange={(event) => updateProject(index, 'stack', event.target.value)}/></label><label className="portfolio-field"><span>Live project URL · optional</span><input type="url" value={item.liveUrl || ''} onChange={(event) => updateProject(index, 'liveUrl', event.target.value)} placeholder="https://"/></label><label className="portfolio-field"><span>Source code URL · optional</span><input type="url" value={item.sourceUrl || ''} onChange={(event) => updateProject(index, 'sourceUrl', event.target.value)} placeholder="https://"/></label></div></article>)}</div></section>
    <section className="editor-card"><div className="editor-card-heading"><span className="editor-section-icon"><Sparkles size={17}/></span><div><h2>Skills &amp; certifications</h2><p>Capability groups and credentials displayed on your page.</p></div></div><div className="editor-subsection-heading"><strong>Skill groups</strong><button type="button" className="editor-add-button" onClick={() => update('skills', [...draft.skills, { name: '', items: '' }])}><Plus size={14}/> Add skill group</button></div><div className="editor-repeat-list">{draft.skills.map((item, index) => <div className="editor-inline-card" key={index}><label className="portfolio-field"><span>Group name</span><input value={item.name} onChange={(event) => updateSkill(index, 'name', event.target.value)}/></label><label className="portfolio-field"><span>Skills · separated by ·</span><input value={item.items} onChange={(event) => updateSkill(index, 'items', event.target.value)}/></label><button type="button" className="editor-remove-button" onClick={() => removeDraftItem(item.name || `skill group ${index + 1}`, () => update('skills', draft.skills.filter((_, i) => i !== index)))} aria-label="Remove skill group"><Trash2 size={14}/></button></div>)}</div><div className="editor-subsection-heading"><strong>Certifications</strong><button type="button" className="editor-add-button" onClick={() => update('certifications', [...draft.certifications, ''])}><Plus size={14}/> Add certification</button></div><div className="editor-cert-list">{draft.certifications.map((certificate, index) => <div className="editor-inline-card" key={index}><label className="portfolio-field"><span>Certification {index + 1}</span><input value={certificate} onChange={(event) => update('certifications', draft.certifications.map((item, i) => i === index ? event.target.value : item))}/></label><button type="button" className="editor-remove-button" onClick={() => removeDraftItem(certificate || `certification ${index + 1}`, () => update('certifications', draft.certifications.filter((_, i) => i !== index)))} aria-label="Remove certification"><Trash2 size={14}/></button></div>)}</div></section>
    <section className="editor-card"><div className="editor-card-heading"><span className="editor-section-icon"><GraduationCap size={17}/></span><div><h2>Education</h2><p>Academic background displayed on your public portfolio.</p></div></div><div className="editor-fields-grid">{field('Degree / qualification', 'degree')}{field('Institution', 'institution')}{field('Period', 'educationPeriod')}{field('Result / distinction', 'educationResult')}</div></section>
    <section className="editor-card"><div className="editor-card-heading"><span className="editor-section-icon"><UserRound size={17}/></span><div><h2>Contact &amp; extra fields</h2><p>Choose how people can reach you and add custom details.</p></div></div><div className="editor-fields-grid">{field('Email', 'email', '', false, 'email')}{field('Phone', 'phone', '', false, 'tel')}{field('LinkedIn URL', 'linkedin', 'https://', false, 'url')}{field('GitHub URL', 'github', 'https://', false, 'url')}{field('Résumé download path', 'resumePath')}</div><div className="editor-subsection-heading"><strong>Custom portfolio fields</strong><button type="button" className="editor-add-button" onClick={() => update('customFields', [...draft.customFields, { label: '', value: '' }])}><Plus size={14}/> Add custom field</button></div><p className="editor-helper">Custom fields appear in the additional details area of the public page.</p>{draft.customFields.map((item, index) => <div className="editor-inline-card" key={index}><label className="portfolio-field"><span>Field label</span><input value={item.label} onChange={(event) => update('customFields', draft.customFields.map((field, i) => i === index ? { ...field, label: event.target.value } : field))}/></label><label className="portfolio-field"><span>Value</span><input value={item.value} onChange={(event) => update('customFields', draft.customFields.map((field, i) => i === index ? { ...field, value: event.target.value } : field))}/></label><button type="button" className="editor-remove-button" onClick={() => removeDraftItem(item.label || `custom field ${index + 1}`, () => update('customFields', draft.customFields.filter((_, i) => i !== index)))} aria-label="Remove custom field"><Trash2 size={14}/></button></div>)}</section>
    <div className="editor-bottom-actions"><p>Remember to save your changes before viewing the public portfolio.</p><button type="button" className="editor-save-button" onClick={() => void save()} disabled={saving}><Save size={15}/> {saving ? 'Saving…' : 'Save portfolio changes'}</button></div>
  </div>;
}
